### ISSUE TITLE
Add xNVSE messages

### ISSUE THREAD

**Issue by pStyl3** [loot/falloutnv#223]
[NVSE](http://nvse.silverlock.org/)
[xNVSE](https://github.com/xNVSE/NVSE)

Quote from NVSE's `http://nvse.silverlock.org/` website:
> NVSE is currently maintained by a group of New Vegas modders: latest releases | source code

As @RacerBG has suggested, we should inform our users if their xNVSE version is up to date or not. For this we first would need to add the `&versionOldX` and `&versionUpToDateX` message anchors to the FNV masterlist, after that we can add the following to the `globals` section of the masterlist:
```
# Latest Version
  # xNVSE
  - <<: *versionOldX
    subs: [ '**Script Extender ([xNVSE](https://github.com/xNVSE/NVSE/releases))**' ]
    condition: 'version("../nvse_loader.exe", "0.6.2.4", <) and file("../nvse_loader.exe")'
  - <<: *versionUpToDateX
    subs: [ '**Script Extender ([xNVSE](https://github.com/xNVSE/NVSE/releases))**' ]
    condition: 'version("../nvse_loader.exe", "0.6.2.4", >=) and file("../nvse_loader.exe")'
```
xNVSE is updated regularly often, so we likely should check once a month (if not more often) if there is a new version available.

Case in point why this would be a good idea is that there are already popular mods using and requiring the very latest version of xNVSE, e.g. [JIP LN NVSE Plugin](https://www.nexusmods.com/newvegas/mods/58277).

We also should think about if we should recommend to update to xNVSE if the original NVSE is still being used. If we were to use existing message anchors for this message, `&obsolete` or better `&useInstead` could be used. Though we also could create a new message anchor, that describes the situation a bit better.

**Comment by IllusiveMan196** [comment]
Like the idea and in case it's helpful - tere is also this mod-thing that's checking in-game for a bunch of plugin updates. [SUPDate Checker(NVSE-Nexus API-GitHub)](https://www.nexusmods.com/newvegas/mods/74504)

**Comment by sibir-ine** [comment]
Considering the wording in the NVSE site suggests xNVSE is the official continuation, I think it'd be justified to warn users if they're not up-to-date with the latest release of xNVSE. I'll add some messages like the ones in the SSE masterlist for SKSE.

I'll also add a version compatibility message in case someone still has an older version of FNV & attempts to use a newer version of NVSE. However, it should be sufficient to just check against the current version of FNV & not older versions since there are probably too few instances of people sticking to a specific older patch version to warrant the extra effort.

One thing to keep in mind is that the last version to support the German no gore version is the last non-xNVSE version (i.e., 5.1 Beta 04). I'm not sure how many people use this version of the game & would be confused by a message telling them to update to xNVSE when it doesn't support their version of the game. I'm also not sure how one can differentiate between the original & the German no gore versions of the game. If it's a small enough edge-case & there isn't a reliable way to tell the two apart, we can proceed without any special consideration for this version. @pStyl3, do you happen to have any experience with this version of the game?

Also, for keeping track of xNVSE updates, you can get notifications for new releases from the xNVSE repo (I already do).

**Comment by pStyl3** [comment]
> do you happen to have any experience with this version of the game?

In the case of Fallout 3 on Steam, the german no gore version is shipped as a different executable, so instead of `Fallout3.exe` you had `Fallout3ng.exe`. For more information on this, see these instructions I provided for Kelmych's Fallout 3 guide [Clear and Present Danger](https://stepmodifications.org/wiki/Fallout3:Unofficial-Kelmych-1.0.0#Pre-Installation_Checklist).

When it comes to FNV, I own the [Ultimate Version](https://store.steampowered.com/sub/13435/) of it on Steam, and while the steam page for the core FNV game ([Link](https://store.steampowered.com/app/22380/Fallout_New_Vegas/)) reads
> Gewaltgemindert: Jugendfreie Version - nur auf Deutsch verfügbar
> Reduced violence: Youthfree version - only available in German

the ultimate version is the normal gore one (and I can play it in English). Because of how they did it with FO3 I would already suspect, that they also provide a different executable, like `FalloutNVng.exe`, if you only buy the core version (and live in Germany). That seems to be supported by [this help request on Steam](https://steamcommunity.com/app/22380/discussions/0/616199736997737285/) too.

So to come back to this issue, I think we could likely use a `file()` condition that looks up `FalloutNVng.exe`.

**Comment by IllusiveMan196** [comment]
Nope, apparently not. [SteamDB](https://steamdb.info/depot/22387/) data on the relevant depot
Interestingly enough [low violence](https://steamdb.info/depot/22305/) depot for original Fallout 3 has both executables, while[ GOTY (German)](https://steamdb.info/depot/22373/) doesn't

**Comment by pStyl3** [comment]
Seems you are right, that discussion I linked must be about some incorrect error message.

**Comment by sibir-ine** [comment]
I was going to say that we can use the fact that a no gore version of `nvse_1_4.dll`, `nvse_1_4ng.dll`, is provided by NVSE for no gore support, but the installation instructions for NVSE say to simply place all bundled DLLs & EXEs in the FNV directory. As a result, I assume checking for the no gore version this way would pick up a lot of false positives. If someone has this version of the game & can find some way to reliably tell them apart, we can add consideration for it, but I think we can just add the messages for now.

**Comment by sibir-ine** [comment]
I've added the messages along with some tangentially related messages, updates, & corrections. I opted to distinguish between the NoGore & non-NoGore versions as I assume most people still using v5.1b4 are using it for the NG support. The website refers users to xNVSE & to v5.1b4 as archived, so I assume very few users would mistakenly download that version. I also created separate versions for the NG version & explicitly referred to it, so hopefully this will provide enough impetus for non-NG users with v5.1b4 or older & who installed the NG DLL as well to notice that we picked up their NG DLL & that they should rectify their NVSE installation.
